import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '../../components/layout/layout'
import Header from '../../components/header/Header'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Personal Blogging App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className='nav'>
            <h1>Personal Blogging App</h1>
            <h1><Link href="/Login">Login</Link></h1>          
        </nav>
        <div>
        <Layout>
         
      <h1>Good Morning App</h1>
      {/* Display a list of recent blog posts here */}
    </Layout>
        </div>


    </>
  )
}
